app:
  storage:
    type: ${APP_STORAGE_TYPE:s3}
    local:
      base-path: ${APP_STORAGE_LOCAL_BASE-PATH:/var/app/uploads}
      base-url:  ${APP_STORAGE_LOCAL_BASE-URL:http://localhost:8080/file/}
    s3:
      bucket: ${APP_STORAGE_S3_BUCKET:citizen-science-io}
      region: ${APP_STORAGE_S3_REGION:ap-southeast-3}
      prefix: ${APP_STORAGE_S3_PREFIX:uploads/}
      url-minutes: ${APP_STORAGE_S3_URL-MINUTES:10}
      access-key: ${APP_STORAGE_S3_ACCESS-KEY:}
      secret-key: ${APP_STORAGE_S3_SECRET-KEY:}
jwt:
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:-1}
#logging:
#  level:
#    root: ${LOGGING_LEVEL_ROOT:DEBUG}
server:
  error:
    whitelabel:
      enabled: ${SERVER_ERROR_WHITELABEL_ENABLED:true}
  port: ${PORT:80}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI-MAXIMUM-POOL-SIZE:10}
      minimum-idle: ${SPRING_DATASOURCE_HIKARI-MAXIMUM-IDLE:2}
      connection-timeout: ${SPRING_DATASOURCE_HIKARI-CONNECTION-TIMEOUT:30000}
      idle-timeout: ${SPRING_DATASOURCE_HIKARI-IDLE-TIMEOUT:600000}
      max-lifetime: ${SPRING_DATASOURCE_HIKARI-MAX-LIFETIME:1800000}
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:false}
    show-sql: ${SPRING_JPA_HIBERNATE_SHOW-SQL:false}
  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE:10MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE:10MB}
  thymeleaf:
    cache: ${SPRING_THYMELEAF_CACHE:true}
  web:
    resources:
      static-locations: classpath:/static/