app:
  storage:
    type: ${APP_STORAGE_TYPE:s3}
    local:
      base-path: ${APP_STORAGE_LOCAL_BASE-PATH:/var/app/uploads}
      base-url:  ${APP_STORAGE_LOCAL_BASE-URL:http://localhost:8080/file/}
    s3:
      bucket: ${APP_STORAGE_S3_BUCKET:citizen-science-io}
      region: ${APP_STORAGE_S3_REGION:ap-southeast-3}
      prefix: ${APP_STORAGE_S3_PREFIX:uploads/}
      url-minutes: ${APP_STORAGE_S3_URL-MINUTES:10}
      access-key: ${APP_STORAGE_S3_ACCESS-KEY:}
      secret-key: ${APP_STORAGE_S3_SECRET-KEY:}
jwt:
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:-1}
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:DEBUG}
server:
  error:
    whitelabel:
      enabled: ${SERVER_ERROR_WHITELABEL_ENABLED:true}
  port: ${PORT:80}
spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:}
      database: ${SPRING_DATA_MONGODB_DATABASE:nnfl}
  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE:10MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE:10MB}
  thymeleaf:
    cache: ${SPRING_THYMELEAF_CACHE:false}
  web:
    resources:
      static-locations: classpath:/static/
openai:
  api-key: ${OPENAI_API-KEY:}
  model: ${OPENAI_MODEL:gpt-4.1-mini}
  max-output-tokens: ${OPENAI_MAX-OUTPUT-TOKENS:512}
  base-url: ${OPENAI_BASE-URL:https://api.openai.com/v1}
  organization-id: ${OPENAI_ORGANIZATION-ID:}
  embedding-model: ${OPENAI_EMBEDDING-MODEL:text-embedding-3-small}
  timeout: ${OPENAI_TIMEOUT:PT60S}
  max-retries: ${OPENAI_MAX-RETRIES:3}

material-search:
  enabled: ${MATERIAL-SEARCH_ENABLED:true}
  collection-name: ${MATERIAL-SEARCH_COLLECTION-NAME:material_embeddings}
  index-name: ${MATERIAL-SEARCH_INDEX-NAME:material_embeddings_index}
  create-index: ${MATERIAL-SEARCH_CREATE-INDEX:true}
  max-results: ${MATERIAL-SEARCH_MAX-RESULTS:5}
  min-score: ${MATERIAL-SEARCH_MIN-SCORE:0.0}