package io.sci.nnfl.model;

public enum MaterialStage {
  I1_GEO_DEPOSITION, I2_MINING_MILLING, I3_CONV_ENR_FUEL, I4_MOX, I5_FRESH_FUEL,
  I6_SPENT_FUEL, I7_REPROCESSING, I8_HLW, I9_SEALED_SRC, I10_UNSEALED_SRC
}
