package io.sci.nnfl.model;

public enum Stage {
    GEOLOGICAL_DEPOSITION,
    MINING_MILLING_EXTRACTION,
    CONVERSION_ENRICHMENT_FUEL_PRODUCTION,
    MOX_FUEL_FABRICATION,
    FRESH_NUCLEAR_FUEL,
    IRRADIATED_NUCLEAR_FUEL,
    REPROCESSING,
    WASTE_PROCESSING,
    SEALED_SOURCE,
    UNSEALED_SOURCE,
    OTHER
}